#!/bin/csh -x

# uses blackbox to solve all of the files matching *.pddl (except for
# the domain.pddl file) and puts the output into *.pddl.out

set Dom = domain.pddl

foreach f (*.pddl)
    if ( $f !~ domain*) then
	blackbox -o $Dom -f $f -g $f.out
    endif
end
