#!/bin/csh

# use blackbox to solve one hw5 problem, writes output to $1.out
# usage: solveone <pddl file>
# e.g.: solveone p00.pddl

if ($#argv != 1) then
  echo "usage: solveone <pddl file>"
else
  echo "Running blackbox -o domain.pddl -f $1 -g $1.out"
  blackbox -o domain.pddl -f $1 -g $1.out
endif


